from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from causal_algo.run_global_pcmci import (
    BLOCKED_ATTENTION_VALUE,
    VARIABLES,
    aggregate_lag_edges,
    apply_topk_filter,
    build_adjacency_matrix,
    build_attention_masks,
    build_physical_prior,
    extract_significant_edges,
    find_project_root,
    load_train_data,
    resolve_repo_path,
    save_outputs,
    split_continuous_segments,
    validate_required_columns,
)
from utils.project_config import load_project_config

try:
    from tigramite import data_processing as pp
    from tigramite.independence_tests.parcorr import ParCorr
    from tigramite.pcmci import PCMCI
except ImportError as exc:  # pragma: no cover - exercised only when dependency is missing
    raise ImportError(
        "Missing dependency `tigramite`. Install the causal-discovery dependencies with:\n"
        "  pip install tigramite networkx scikit-learn pandas numpy matplotlib"
    ) from exc


PROJECT_CONFIG = load_project_config()
os.environ.setdefault("MPLCONFIGDIR", str(PROJECT_CONFIG.get_path("paths.matplotlib_cache")))
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)

DEFAULT_REGIME_TRAIN_PATH = (
    "results/d1_long_no_wind_2015_2022/regimes/"
    "gmm_hmm_daytime_k7/train_with_regime.csv"
)
DEFAULT_OUTPUT_DIR = "results/d1_long_no_wind_2015_2022/causal_graphs/regime_target_pcmci_k7"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build target-regime-conditioned PCMCI graphs from K=7 GMM-HMM regime labels. "
            "For each regime r, the target timestamp is conditioned on regime(t)=r while lagged variables "
            "come from the original continuous timeline."
        )
    )
    parser.add_argument(
        "--regime_train_path",
        default=DEFAULT_REGIME_TRAIN_PATH,
        help="Path to train_with_regime.csv generated by scripts/causal/run_gmm_hmm_daytime_regimes.py.",
    )
    parser.add_argument("--regime_col", default="regime", help="Regime label column.")
    parser.add_argument("--regimes", nargs="+", type=int, default=[1, 2, 3, 4, 5, 6, 7])
    parser.add_argument("--tau_min", type=int, default=1)
    parser.add_argument("--tau_max", type=int, default=12)
    parser.add_argument("--pc_alpha", type=float, default=0.05)
    parser.add_argument("--alpha_level", type=float, default=0.05)
    parser.add_argument("--fdr_method", type=str, default="fdr_bh")
    parser.add_argument("--topk_active", type=int, default=5)
    parser.add_argument("--topk_other", type=int, default=3)
    parser.add_argument("--min_segment_length", type=int, default=24)
    parser.add_argument("--freq_minutes", type=int, default=5)
    parser.add_argument(
        "--mask_type",
        default="y",
        choices=["y"],
        help="Tigramite mask type. Keep 'y' so only target timestamps are regime-conditioned.",
    )
    parser.add_argument("--output_dir", default=DEFAULT_OUTPUT_DIR)
    return parser.parse_args()


def validate_arguments(args: argparse.Namespace) -> None:
    if args.tau_min < 0:
        raise ValueError("--tau_min must be >= 0.")
    if args.tau_max < args.tau_min:
        raise ValueError("--tau_max must be >= --tau_min.")
    if args.tau_max <= 0:
        raise ValueError("--tau_max must be positive.")
    if args.min_segment_length <= args.tau_max:
        raise ValueError("--min_segment_length should be greater than --tau_max.")
    if not 0 < args.pc_alpha <= 1:
        raise ValueError("--pc_alpha must be in (0, 1].")
    if not 0 < args.alpha_level <= 1:
        raise ValueError("--alpha_level must be in (0, 1].")
    if any(regime <= 0 for regime in args.regimes):
        raise ValueError("--regimes should contain daytime regimes only; regime 0 is night and is not supported.")


def prepare_regime_masked_dataframe(
    segments: list[pd.DataFrame],
    variables: list[str],
    regime_col: str,
    regime_id: int,
    dropped_missing_rows: int,
) -> tuple[pp.DataFrame, dict[str, Any]]:
    if any(segment[variables + [regime_col]].isna().any(axis=None) for segment in segments):
        raise ValueError("Missing values must be dropped before segment detection.")

    scaler_source = pd.concat([segment.loc[:, variables] for segment in segments], axis=0)
    std = scaler_source.std(ddof=0)
    constant_columns = [column for column in variables if pd.isna(std[column]) or np.isclose(std[column], 0.0)]
    if constant_columns:
        raise ValueError(
            "PCMCI variables contain constants after row filtering, which makes ParCorr ill-conditioned.\n"
            f"Constant columns: {constant_columns}"
        )

    scaler = StandardScaler()
    scaler.fit(scaler_source.loc[:, variables].to_numpy(dtype=np.float64))

    segment_dict: dict[int, np.ndarray] = {}
    mask_dict: dict[int, np.ndarray] = {}
    segment_lengths: list[int] = []
    target_regime_rows_in_segments = 0
    for segment_id, segment in enumerate(segments):
        values = scaler.transform(segment.loc[:, variables].to_numpy(dtype=np.float64)).astype(np.float64)
        target_mask_1d = (segment[regime_col].to_numpy(dtype=np.int64) != int(regime_id))
        mask = np.repeat(target_mask_1d[:, None], len(variables), axis=1)
        if values.shape[0] > 0:
            segment_dict[segment_id] = values
            mask_dict[segment_id] = mask.astype(bool)
            segment_lengths.append(int(values.shape[0]))
            target_regime_rows_in_segments += int((~target_mask_1d).sum())

    if target_regime_rows_in_segments <= 0:
        raise ValueError(f"No target rows for regime {regime_id} remain after segment filtering.")

    if len(segment_dict) == 1:
        analysis_mode = "single"
        data_arrays: dict[int, np.ndarray] | np.ndarray = next(iter(segment_dict.values()))
        mask_arrays: dict[int, np.ndarray] | np.ndarray = next(iter(mask_dict.values()))
    else:
        analysis_mode = "multiple"
        data_arrays = segment_dict
        mask_arrays = mask_dict

    dataframe = pp.DataFrame(data_arrays, mask=mask_arrays, var_names=variables, analysis_mode=analysis_mode)
    metadata = {
        "analysis_mode": analysis_mode,
        "rows_used_in_pcmci": int(sum(segment_lengths)),
        "continuous_segments_kept": int(len(segment_lengths)),
        "segment_lengths_kept": segment_lengths,
        "target_regime_rows_in_segments": int(target_regime_rows_in_segments),
        "dropped_missing_rows_in_variables": int(dropped_missing_rows),
        "scaler_mean": [float(value) for value in scaler.mean_],
        "scaler_scale": [float(value) for value in scaler.scale_],
    }
    return dataframe, metadata


def run_target_masked_pcmci(
    dataframe: pp.DataFrame,
    tau_min: int,
    tau_max: int,
    pc_alpha: float,
    alpha_level: float,
    fdr_method: str,
    mask_type: str,
) -> dict[str, Any]:
    try:
        cond_ind_test = ParCorr(significance="analytic", mask_type=mask_type)
    except TypeError:
        cond_ind_test = ParCorr(significance="analytic")
        if hasattr(cond_ind_test, "set_mask_type"):
            cond_ind_test.set_mask_type(mask_type)
        else:
            setattr(cond_ind_test, "mask_type", mask_type)

    pcmci = PCMCI(
        dataframe=dataframe,
        cond_ind_test=cond_ind_test,
        verbosity=0,
    )
    try:
        return pcmci.run_pcmci(
            tau_min=tau_min,
            tau_max=tau_max,
            pc_alpha=pc_alpha,
            alpha_level=alpha_level,
            fdr_method=fdr_method,
        )
    except TypeError:
        return pcmci.run_pcmci(
            tau_max=tau_max,
            pc_alpha=pc_alpha,
            alpha_level=alpha_level,
            fdr_method=fdr_method,
        )


def build_regime_config(
    args: argparse.Namespace,
    regime_id: int,
    regime_output_dir: Path,
    train_path: Path,
    time_col: str,
    rows_loaded: int,
    selected_rows: int,
    target_regime_rows_raw: int,
    total_segments_after_filter: int,
    dropped_short_segments: int,
    all_segment_lengths: list[int],
    prepared: dict[str, Any],
    raw_significant_count: int,
    filtered_by_prior_count: int,
    prior_allowed_count: int,
    aggregated_count: int,
    topk_count: int,
    effective_p_matrix_source: str,
    runtime_seconds: float,
) -> dict[str, Any]:
    return {
        "script": "scripts/causal/run_regime_target_pcmci.py",
        "train_path": str(train_path),
        "output_dir": str(regime_output_dir),
        "time_column": time_col,
        "sample_policy": "train_with_regime.csv only; validation/calibration/test are never read",
        "sample_scope": "target-regime-conditioned train samples",
        "regime_id": int(regime_id),
        "regime_condition": "target_time_only",
        "regime_condition_detail": (
            "Rows are masked according to regime(t)=r only at the target Y timestamp. "
            "Lagged X/Z variables are taken from the original continuous time axis and are not required "
            "to have the same regime."
        ),
        "mask_type": args.mask_type,
        "regime_column": args.regime_col,
        "freq_minutes": args.freq_minutes,
        "raw_train_samples": int(rows_loaded),
        "selected_train_samples": int(selected_rows),
        "target_regime_rows_raw": int(target_regime_rows_raw),
        "target_regime_rows_in_pcmci_segments": int(prepared["target_regime_rows_in_segments"]),
        "rows_used_in_pcmci": int(prepared["rows_used_in_pcmci"]),
        "total_segments_after_filter": int(total_segments_after_filter),
        "continuous_segments_kept": int(prepared["continuous_segments_kept"]),
        "segments_dropped_for_being_short": int(dropped_short_segments),
        "segment_lengths_all": all_segment_lengths,
        "segment_lengths_kept": prepared["segment_lengths_kept"],
        "dropped_missing_rows_in_variables": int(prepared["dropped_missing_rows_in_variables"]),
        "analysis_mode": prepared["analysis_mode"],
        "tau_min": args.tau_min,
        "tau_max": args.tau_max,
        "pc_alpha": args.pc_alpha,
        "alpha_level": args.alpha_level,
        "fdr_method": args.fdr_method,
        "topk_active": args.topk_active,
        "topk_other": args.topk_other,
        "raw_significant_lag_edges": int(raw_significant_count),
        "physical_prior_filtered_lag_edges": int(filtered_by_prior_count),
        "prior_allowed_lag_edges": int(prior_allowed_count),
        "aggregated_edges_before_topk": int(aggregated_count),
        "aggregated_edges_after_topk": int(topk_count),
        "effective_p_matrix_source": effective_p_matrix_source,
        "graph_semantics": (
            "Target-regime-conditioned, prior-constrained PCMCI-derived Granger-style temporal dependency graph. "
            "For regime r, samples are selected by the target timestamp regime(t)=r while lagged variables remain "
            "on the original continuous timeline. This is not a within-regime-only graph and not a definitive "
            "structural causal graph."
        ),
        "adjacency_direction": "adjacency[target, source] = 1; target query may attend to source key/value",
        "mask_format": {
            "global_causal_mask.npy": "binary adjacency, 1=allowed, 0=blocked",
            "global_additive_attention_mask.npy": f"additive mask, 0.0=allowed, {BLOCKED_ATTENTION_VALUE}=blocked",
        },
        "physical_prior": build_physical_prior(VARIABLES),
        "standard_scaler": {
            "fit_scope": "all retained continuous train rows in train_with_regime.csv",
            "mean": prepared["scaler_mean"],
            "scale": prepared["scaler_scale"],
        },
        "runtime_seconds": float(runtime_seconds),
        "generated_at": pd.Timestamp.now().isoformat(),
    }


def summarize_active_parents(regime_id: int, active_parents_path: Path) -> list[dict[str, Any]]:
    if not active_parents_path.exists():
        return []
    parents = pd.read_csv(active_parents_path)
    rows: list[dict[str, Any]] = []
    for row in parents.itertuples(index=False):
        rows.append(
            {
                "regime": int(regime_id),
                "source": row.source,
                "target": row.target,
                "significant_lags": row.significant_lags,
                "strongest_lag": int(row.strongest_lag),
                "max_abs_mci": float(row.max_abs_mci),
                "signed_mci_at_strongest_lag": float(row.signed_mci_at_strongest_lag),
                "min_p_value": float(row.min_p_value),
                "sign": row.sign,
                "lag_count": int(row.lag_count),
            }
        )
    return rows


def write_markdown_summary(output_dir: Path, summary_df: pd.DataFrame, active_parent_df: pd.DataFrame) -> None:
    lines = [
        "# K=7 Target-Regime-Conditioned PCMCI Experiment",
        "",
        "## Semantics",
        "",
        "For each regime r, PCMCI samples are selected by `regime(t)=r` at the target timestamp only. "
        "Lagged variables are taken from the original continuous train timeline and are not required to share the target regime.",
        "",
        "## Regime Summary",
        "",
        "| Regime | Target rows | Rows used | Segments | Raw edges | Prior edges | Top-K edges | Mask density |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in summary_df.itertuples(index=False):
        lines.append(
            f"| {int(row.regime)} | {int(row.target_regime_rows_in_pcmci_segments)} | "
            f"{int(row.rows_used_in_pcmci)} | {int(row.continuous_segments_kept)} | "
            f"{int(row.raw_significant_lag_edges)} | {int(row.prior_allowed_lag_edges)} | "
            f"{int(row.aggregated_edges_after_topk)} | {float(row.mask_density):.2%} |"
        )

    lines.extend(["", "## Active_Pow Parents", ""])
    if active_parent_df.empty:
        lines.append("No Active_Pow parent edges were retained after prior and Top-K filtering.")
    else:
        lines.extend(
            [
                "| Regime | Source | Lags | Strongest lag | |MCI| | p-value | Sign |",
                "|---:|---|---|---:|---:|---:|---|",
            ]
        )
        for row in active_parent_df.itertuples(index=False):
            lines.append(
                f"| {int(row.regime)} | {row.source} | {row.significant_lags} | "
                f"{int(row.strongest_lag)} | {float(row.max_abs_mci):.4f} | "
                f"{float(row.min_p_value):.3g} | {row.sign} |"
            )

    (output_dir / "regime_target_pcmci_experiment.md").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    args = parse_args()
    validate_arguments(args)

    project_root = find_project_root()
    train_path = resolve_repo_path(args.regime_train_path, project_root)
    output_dir = resolve_repo_path(args.output_dir, project_root)

    print(f"Loading regime-labeled train split only: {train_path}")
    train_df, time_col, rows_loaded = load_train_data(train_path)
    validate_required_columns(train_df, VARIABLES)
    if args.regime_col not in train_df.columns:
        raise KeyError(f"Missing required regime column: {args.regime_col}")

    required_columns = VARIABLES + [args.regime_col]
    missing_mask = train_df[required_columns].isna().any(axis=1)
    dropped_missing_rows = int(missing_mask.sum())
    if dropped_missing_rows:
        print(f"Dropping {dropped_missing_rows} rows with missing PCMCI/regime columns before segment detection.")
    pcmci_source_df = train_df.loc[~missing_mask].copy()
    selected_rows = len(pcmci_source_df)
    if pcmci_source_df.empty:
        raise ValueError("No usable rows remain after dropping missing values.")

    segments, all_segment_lengths, dropped_short_segments = split_continuous_segments(
        pcmci_source_df,
        time_col=time_col,
        freq_minutes=args.freq_minutes,
        min_segment_length=args.min_segment_length,
    )

    summary_rows: list[dict[str, Any]] = []
    active_parent_rows: list[dict[str, Any]] = []
    for regime_id in args.regimes:
        start_time = time.time()
        target_regime_rows_raw = int((pcmci_source_df[args.regime_col].astype(int) == int(regime_id)).sum())
        if target_regime_rows_raw <= 0:
            raise ValueError(f"No target rows found for regime {regime_id}.")

        regime_output_dir = output_dir / f"regime_{regime_id}"
        print(
            f"Running target-regime-conditioned PCMCI for regime {regime_id} "
            f"(target rows={target_regime_rows_raw}, tau={args.tau_min}..{args.tau_max})"
        )

        dataframe, prepared = prepare_regime_masked_dataframe(
            segments=segments,
            variables=VARIABLES,
            regime_col=args.regime_col,
            regime_id=regime_id,
            dropped_missing_rows=dropped_missing_rows,
        )
        results = run_target_masked_pcmci(
            dataframe=dataframe,
            tau_min=args.tau_min,
            tau_max=args.tau_max,
            pc_alpha=args.pc_alpha,
            alpha_level=args.alpha_level,
            fdr_method=args.fdr_method,
            mask_type=args.mask_type,
        )

        extracted_edges = extract_significant_edges(
            results=results,
            variables=VARIABLES,
            alpha_level=args.alpha_level,
            tau_min=args.tau_min,
            tau_max=args.tau_max,
            fdr_method=args.fdr_method,
        )
        aggregated_edges = aggregate_lag_edges(extracted_edges.prior_allowed_lag_edges)
        topk_edges = apply_topk_filter(aggregated_edges, topk_active=args.topk_active, topk_other=args.topk_other)
        adjacency = build_adjacency_matrix(topk_edges, VARIABLES)
        binary_mask, additive_mask = build_attention_masks(adjacency)

        elapsed_seconds = time.time() - start_time
        config = build_regime_config(
            args=args,
            regime_id=regime_id,
            regime_output_dir=regime_output_dir,
            train_path=train_path,
            time_col=time_col,
            rows_loaded=rows_loaded,
            selected_rows=selected_rows,
            target_regime_rows_raw=target_regime_rows_raw,
            total_segments_after_filter=len(all_segment_lengths),
            dropped_short_segments=dropped_short_segments,
            all_segment_lengths=all_segment_lengths,
            prepared=prepared,
            raw_significant_count=extracted_edges.raw_significant_count,
            filtered_by_prior_count=extracted_edges.filtered_by_prior_count,
            prior_allowed_count=len(extracted_edges.prior_allowed_lag_edges),
            aggregated_count=len(aggregated_edges),
            topk_count=len(topk_edges),
            effective_p_matrix_source=extracted_edges.effective_p_matrix_source,
            runtime_seconds=elapsed_seconds,
        )

        paths = save_outputs(
            output_dir=regime_output_dir,
            results=results,
            fdr_method=args.fdr_method,
            raw_lag_edges=extracted_edges.raw_lag_edges,
            prior_allowed_lag_edges=extracted_edges.prior_allowed_lag_edges,
            aggregated_edges=aggregated_edges,
            topk_edges=topk_edges,
            adjacency=adjacency,
            binary_mask=binary_mask,
            additive_mask=additive_mask,
            config=config,
            variables=VARIABLES,
        )

        mask_density = float(np.sum(binary_mask > 0.0) / binary_mask.size)
        summary_rows.append(
            {
                "regime": int(regime_id),
                "target_regime_rows_raw": int(target_regime_rows_raw),
                "target_regime_rows_in_pcmci_segments": int(prepared["target_regime_rows_in_segments"]),
                "rows_used_in_pcmci": int(prepared["rows_used_in_pcmci"]),
                "continuous_segments_kept": int(prepared["continuous_segments_kept"]),
                "raw_significant_lag_edges": int(extracted_edges.raw_significant_count),
                "physical_prior_filtered_lag_edges": int(extracted_edges.filtered_by_prior_count),
                "prior_allowed_lag_edges": int(len(extracted_edges.prior_allowed_lag_edges)),
                "aggregated_edges_before_topk": int(len(aggregated_edges)),
                "aggregated_edges_after_topk": int(len(topk_edges)),
                "mask_density": mask_density,
                "runtime_seconds": float(elapsed_seconds),
                "output_dir": str(regime_output_dir),
            }
        )
        active_parent_rows.extend(summarize_active_parents(regime_id, paths["active_parents"]))

    output_dir.mkdir(parents=True, exist_ok=True)
    summary_df = pd.DataFrame(summary_rows)
    active_parent_df = pd.DataFrame(active_parent_rows)
    summary_df.to_csv(output_dir / "regime_pcmci_summary.csv", index=False)
    active_parent_df.to_csv(output_dir / "regime_active_pow_parents_summary.csv", index=False)
    write_markdown_summary(output_dir, summary_df, active_parent_df)

    print(f"Finished target-regime-conditioned PCMCI outputs under: {output_dir}")


if __name__ == "__main__":
    main()
